# Generated by Django 4.0.3 on 2022-04-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('from_date', models.DateTimeField(verbose_name='From Date')),
                ('to_date', models.DateTimeField(verbose_name='To Date')),
            ],
        ),
    ]
